// <auto-generated />
using System;
using AutoKeg.ISR.Snapshot.DataTransfer;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace AutoKeg.ISR.Snapshot.Migrations
{
    [DbContext(typeof(CountDataContext))]
    partial class CountDataContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.2-servicing-10034");

            modelBuilder.Entity("AutoKeg.ISR.Snapshot.DataTransfer.PulseDTO", b =>
                {
                    b.Property<int>("PulseCountId")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("Count");

                    b.Property<DateTime>("DateCounted")
                        .IsConcurrencyToken();

                    b.Property<bool>("IsProcessed");

                    b.HasKey("PulseCountId");

                    b.ToTable("PulseCounts");
                });
#pragma warning restore 612, 618
        }
    }
}
